# Generated by Django 5.0.7 on 2024-08-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(max_length=200, upload_to='media/slider_img/')),
                ('brand_name', models.CharField(max_length=200)),
                ('discount_deal', models.CharField(choices=[('new_arrival', 'New Arrival'), ('hot_deals', 'Hot Deals')], max_length=200)),
                ('sale', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
