# Generated by Django 5.0.7 on 2024-08-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_order_order_total_order_packing_cost_order_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('None', 'None'), ('Pending', 'Pending'), ('Complete', 'Complete')], default='None', max_length=10),
        ),
    ]
